
chaos:
  loris:
    url: http://dummy-chaos-loris.com
    applications:
      rel : applications
    chaoses:
      rel: chaoses
    events:
      rel: events
    schedules:
      rel: schedules

organizations:
  system_domain:
    guid: "0123-0123-0123-0123"
    spaces:
      elpaaso-sandbox:
        guid: "1234-1234-1234-1234"
        applications:
          elpaaso-sandbox-service:
            guid: "2345-2345-2345-2345"
          elpaaso-sandbox-ui:
            guid: "3456-3456-3456-3456"
      cf-web-ui:
        guid: "9999-9999-9999-9999"
        applications:
          cf-console:
            guid: "xx12-1234-1234-1234"
schedules:
  hourly:
    expression: "0 0 * * * *"
    name: hourly
  midnight:
    expression: "0 * 0 * * *"
  weekend-midnight:
    expression: "0 * 0 * * SAT-SUN"

